# Generated by Django 5.0.7 on 2024-07-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_api_mjijvr', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
